package com.mai.xmai.basehttp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "sleepblockdata".
 */
public class SleepBlockData {

    private Long id;
    private String snoreCount;
    private String bpmValue;
    private Integer recordCount;
    private String sleepStage;
    private Integer fallAsleepTime;
    private String hasCount;
    private String mac;
    private String blockId;
    private String uid;
    private String movementCount;
    private String createTime;
    private String sleepState;
    private String is5MinuteBlock;
    private String temperature;
    private String startTime;
    private String endTime;
    private Boolean isCommit;
    private String latestUpTime;

    public SleepBlockData() {
    }

    public SleepBlockData(Long id) {
        this.id = id;
    }

    public SleepBlockData(Long id, String snoreCount, String bpmValue, Integer recordCount, String sleepStage, Integer fallAsleepTime, String hasCount, String mac, String blockId, String uid, String movementCount, String createTime, String sleepState, String is5MinuteBlock, String temperature, String startTime, String endTime, Boolean isCommit, String latestUpTime) {
        this.id = id;
        this.snoreCount = snoreCount;
        this.bpmValue = bpmValue;
        this.recordCount = recordCount;
        this.sleepStage = sleepStage;
        this.fallAsleepTime = fallAsleepTime;
        this.hasCount = hasCount;
        this.mac = mac;
        this.blockId = blockId;
        this.uid = uid;
        this.movementCount = movementCount;
        this.createTime = createTime;
        this.sleepState = sleepState;
        this.is5MinuteBlock = is5MinuteBlock;
        this.temperature = temperature;
        this.startTime = startTime;
        this.endTime = endTime;
        this.isCommit = isCommit;
        this.latestUpTime = latestUpTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSnoreCount() {
        return snoreCount;
    }

    public void setSnoreCount(String snoreCount) {
        this.snoreCount = snoreCount;
    }

    public String getBpmValue() {
        return bpmValue;
    }

    public void setBpmValue(String bpmValue) {
        this.bpmValue = bpmValue;
    }

    public Integer getRecordCount() {
        return recordCount;
    }

    public void setRecordCount(Integer recordCount) {
        this.recordCount = recordCount;
    }

    public String getSleepStage() {
        return sleepStage;
    }

    public void setSleepStage(String sleepStage) {
        this.sleepStage = sleepStage;
    }

    public Integer getFallAsleepTime() {
        return fallAsleepTime;
    }

    public void setFallAsleepTime(Integer fallAsleepTime) {
        this.fallAsleepTime = fallAsleepTime;
    }

    public String getHasCount() {
        return hasCount;
    }

    public void setHasCount(String hasCount) {
        this.hasCount = hasCount;
    }

    public String getMac() {
        return mac;
    }

    public void setMac(String mac) {
        this.mac = mac;
    }

    public String getBlockId() {
        return blockId;
    }

    public void setBlockId(String blockId) {
        this.blockId = blockId;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getMovementCount() {
        return movementCount;
    }

    public void setMovementCount(String movementCount) {
        this.movementCount = movementCount;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getSleepState() {
        return sleepState;
    }

    public void setSleepState(String sleepState) {
        this.sleepState = sleepState;
    }

    public String getIs5MinuteBlock() {
        return is5MinuteBlock;
    }

    public void setIs5MinuteBlock(String is5MinuteBlock) {
        this.is5MinuteBlock = is5MinuteBlock;
    }

    public String getTemperature() {
        return temperature;
    }

    public void setTemperature(String temperature) {
        this.temperature = temperature;
    }

    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public String getEndTime() {
        return endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    public Boolean getIsCommit() {
        return isCommit;
    }

    public void setIsCommit(Boolean isCommit) {
        this.isCommit = isCommit;
    }

    public String getLatestUpTime() {
        return latestUpTime;
    }

    public void setLatestUpTime(String latestUpTime) {
        this.latestUpTime = latestUpTime;
    }

    @Override
    public String toString() {
        return "SleepBlockData{" +
                "id=" + id +
                ", snoreCount='" + snoreCount + '\'' +
                ", bpmValue='" + bpmValue + '\'' +
                ", recordCount=" + recordCount +
                ", sleepStage='" + sleepStage + '\'' +
                ", fallAsleepTime=" + fallAsleepTime +
                ", hasCount='" + hasCount + '\'' +
                ", mac='" + mac + '\'' +
                ", blockId='" + blockId + '\'' +
                ", uid='" + uid + '\'' +
                ", movementCount='" + movementCount + '\'' +
                ", createTime='" + createTime + '\'' +
                ", sleepState='" + sleepState + '\'' +
                ", is5MinuteBlock='" + is5MinuteBlock + '\'' +
                ", temperature='" + temperature + '\'' +
                ", startTime='" + startTime + '\'' +
                ", endTime='" + endTime + '\'' +
                ", isCommit=" + isCommit +
                ", latestUpTime='" + latestUpTime + '\'' +
                '}';
    }
}
